### ISSUE TITLE
enable missing features

### ISSUE THREAD

**Issue by muelli** [flathub/org.wireshark.Wireshark#1]
copied from https://github.com/flathub/flathub/pull/809#issuecomment-457121324

Could you look into enabling missing features:

    Compiled (64-bit) with Qt 5.12.0, with libpcap, with POSIX capabilities (Linux),
    without libnl, with GLib 2.58.1, with zlib 1.2.11, without SMI, without c-ares,
    without Lua, with GnuTLS 3.6.5, with Gcrypt 1.8.3, with MIT Kerberos, without
    MaxMind DB resolver, without nghttp2, without LZ4, without Snappy, with libxml2
    2.9.8, with QtMultimedia, without SBC, without SpanDSP, without bcg729.

Features:

    DNS name resolution for IP addresses: c-ares
    Lua plugins/scripting: lua
    Full HTTP/2 support: nghttp2
    GeoIP: libmaxmind (also needs database files for full functionality though)

**Comment by Lekensteyn** [comment]
Highly recommended:
- libssh (for remote capture client): https://www.libssh.org/
- c-ares: https://c-ares.haxx.se/
- Lua 5.2 (not 5.3): https://www.lua.org/download.html
- nghttp2: https://www.nghttp2.org/ (only the library is needed for header parsing, OpenSSL, libev, libevent-openssl and maybe even Jansson should not be needed)
- maxmind: https://github.com/maxmind/libmaxminddb

The netlink (libnl) dependency is needed for wireless (IEEE 802.11) capture functionality. If this is not possible in any way due to the sandbox restrictions, adding it might not be very useful.

If you are going to enable all features any way (like we do for Windows packages):
- Decompression support for the CQL dissector:
  - snappy: https://google.github.io/snappy/
  - lz4: https://lz4.github.io/lz4/
- Additional codec support for the RTP player:
   - bcg729: https://www.linphone.org/technical-corner/bcg729/overview
   - spandsp: https://soft-switch.org/installing-spandsp.html https://soft-switch.org/downloads/spandsp/
   - SBC: https://git.kernel.org/pub/scm/bluetooth/sbc.git

**Comment by muelli** [comment]
I've created https://github.com/flathub/org.wireshark.Wireshark/pull/2

Notice how Lua doesn't build properly and how l4z prevents the Wireshark icon (!) from being found.
I think it's worth it to fix those issues. But I'd leave it as is and wait for somebody else to come and pick it up.

wireshark --version says:

```
Compiled (64-bit) with Qt 5.12.0, with libpcap, with POSIX capabilities (Linux),
without libnl, with GLib 2.58.2, with zlib 1.2.11, without SMI, with c-ares
1.15.0, without Lua, with GnuTLS 3.6.5, with Gcrypt 1.8.3, with MIT Kerberos,
with MaxMind DB resolver, with nghttp2 1.36.0, without LZ4, with Snappy, with
libxml2 2.9.9, with QtMultimedia, with SBC, with SpanDSP, with bcg729.

```

**Comment by Lekensteyn** [comment]
I have no idea how lz4 can prevent the icon from being found... perhaps a conflict with a system library? (I have never tried to build lz4 myself.)

As for Lua, you might have to set some options to build a shared library:
- https://git.archlinux.org/svntogit/packages.git/tree/trunk/liblua.so.patch?h=packages/lua52
- https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/lua52

**Comment by muelli** [comment]
I think everything but lz4 (https://github.com/flathub/org.wireshark.Wireshark/pull/3) and GeoIP (https://github.com/flathub/org.wireshark.Wireshark/issues/17) has been added.
